<?xml version="1.0" encoding="utf-8"?><Database Name="EducationalSystem" Class="EducationalSystemDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(local);Initial Catalog=EducationalSystem;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="_2_LogIn.Properties.Settings" SettingsPropertyName="EducationalSystemConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tb_Messege" Member="tb_Messege">
    <Type Name="tb_Messege">
      <Column Name="No" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Detail" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Category" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Sender" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SendTime" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_Notice" Member="tb_Notice">
    <Type Name="tb_Notice">
      <Column Name="No" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Detail" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Category" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Sender" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SendTime" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_Student" Member="tb_Student">
    <Type Name="tb_Student">
      <Column Name="No" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="Char(40)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="BirthDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Class" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="Char(11)" CanBeNull="true" />
      <Column Name="Resume" Type="System.Xml.Linq.XElement" DbType="Xml" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Portrait" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.tb_StudentPersonal" Member="tb_StudentPersonal">
    <Type Name="tb_StudentPersonal">
      <Column Name="No" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Question1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Answer1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Question2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Answer2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>